### ISSUE TITLE
The extension crashes in Chrome v.66

### ISSUE THREAD

**Issue by makfruit** [leonid-shevtsov/send_to_omnifocus.crx#10]
Hi,

Couple weeks ago, the extension stopped working properly — when I click it, Chrome crashes, nothing is added to Omnifocus. 

Screencast: http://take.ms/pthfc

System: 
- MacOS 10.13.3
- Chrome Version 66.0.3359.81 (Official Build) beta (64-bit)

Can you look into it?

Thanks,

**Comment by leonid-shevtsov** [comment]
Thanks for reporting! The crashing should be fixed in version 2.2.0
