### ISSUE TITLE
Setup to omnifocus account

### ISSUE THREAD

**Issue by xabi24** [leonid-shevtsov/send_to_omnifocus.crx#8]
Hello, I find your chrome extension "Send to omnifocus" very interesting , I do love the platform. There is just a small thing I don't seem to get. How do i input my personal inbox omnifocus email address? I just can't find how to do it.

**Comment by leonid-shevtsov** [comment]
Thanks! The extension works with the Omnifocus app launched on the same machine as Google Chrome, so you don't have to set up an account. It just works (or doesn't, if there is no Omnifocus installed.)
