### ISSUE TITLE
Clipping fails with 'Cannot read property 'title' of undefined' on certain pages

### ISSUE THREAD

**Issue by wpp** [leonid-shevtsov/send_to_omnifocus.crx#9]
Hi,

first of all thanks for the extension love using it. Today I noticed clipping failed with

> Cannot read property 'title' of undefined

![screen shot 2016-05-25 at 13 29 46](https://cloud.githubusercontent.com/assets/942021/15538503/ea7e3274-227c-11e6-8147-5df38d0f0497.png)
when invoking it on https://google.github.io/styleguide/javascriptguide.xml.

Cheers

**Comment by leonid-shevtsov** [comment]
Thanks for reporting! 

I'm fairly sure that this happened because the document is not HTML but [XSLT](https://en.wikipedia.org/wiki/Xslt)-formatted XML, and thus it doesn't have a `document` object and no `document.title`.

I'll fix this for the next release (whenever that happens).
